# Project: XORSBOXnet
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = XORSBOXnet_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/sjoshia/AppData/Local/Continuum/anaconda3/include"
CXXINCS  = -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/sjoshia/Documents/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/sjoshia/AppData/Local/Continuum/anaconda3/include"
BIN      = XORSBOXnet.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

XORSBOXnet_private.res: XORSBOXnet_private.rc 
	$(WINDRES) -i XORSBOXnet_private.rc --input-format=rc -o XORSBOXnet_private.res -O coff 

